[project]
name = "web_scraper"
version = "0.0.1"
description = ""
authors = [
    { name = "Name <Email>" }
]
license = { text = "MIT" }
requires-python = ">=3.10"

dependencies = [
    "agentstack[crewai]>=0.3.1",
    "firecrawl-py>=1.6.4",
    "neon-api>=0.1.5",
    "psycopg2-binary==2.9.10",
]
